Repository FISub/backend, pull requests merged in 2024-08, with the labels that each got.

#2 spring data jpa 사용 예제
  build.gradle
  src/main/java/com/woorifisa/backend/ex/MemberController.java
  src/main/java/com/woorifisa/backend/ex/MemberDTO.java
  src/main/java/com/woorifisa/backend/ex/MemberEx.java
  src/main/java/com/woorifisa/backend/ex/MemberRepository.java
  src/main/java/com/woorifisa/backend/ex/MemberService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: enhancement

#4 application.properties gitignore에 반영 및 swagger 사용 예제 추가
  .gitignore
  build.gradle
  src/main/java/com/woorifisa/backend/ex/MemberController.java
  src/main/java/com/woorifisa/backend/test/TestController.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#6 #5 feat : update 방식에 대한 논의를 위한 samplecode 추가
  src/main/java/com/woorifisa/backend/ex/MemberEx.java
  src/main/java/com/woorifisa/backend/ex/MemberRepository.java
  src/main/java/com/woorifisa/backend/ex/MemberService.java
Labels: question

#8 add: 공통파일 common 생성 & fix: dto common으로 이동
  src/main/java/com/woorifisa/backend/common/config/WebConfig.java
  src/main/java/com/woorifisa/backend/common/dto/MemberDTO.java
  src/main/java/com/woorifisa/backend/common/dto/ProductDTO.java
  src/main/java/com/woorifisa/backend/test/TestController.java
  src/main/java/com/woorifisa/backend/test/TestService.java
  src/main/java/com/woorifisa/backend/test/TestServiceImpl.java
Labels: enhancement

#9 add: ReviewDTO 추가
  src/main/java/com/woorifisa/backend/common/dto/ReviewDTO.java
Labels: enhancement

#10 feat:PaymentDTO 추가
  src/main/java/com/woorifisa/backend/common/dto/PaymentDTO.java
Labels: enhancement

#11 feat : Service 인터페이스화 후 ServiceImpl 추가 SubscriptionDTO 추가
  src/main/java/com/woorifisa/backend/common/dto/SubscriptionDTO.java
  src/main/java/com/woorifisa/backend/ex/MemberService.java
  src/main/java/com/woorifisa/backend/ex/MemberServiceImple.java
Labels: enhancement

#12 feat:Entity 추가 & 회원가입(test) 기능 추가
  src/main/java/com/woorifisa/backend/common/entity/Member.java
  src/main/java/com/woorifisa/backend/common/entity/Payment.java
  src/main/java/com/woorifisa/backend/common/entity/Product.java
  src/main/java/com/woorifisa/backend/common/entity/Review.java
  src/main/java/com/woorifisa/backend/common/entity/Subscription.java
  src/main/java/com/woorifisa/backend/test/MemberRepository2.java
  src/main/java/com/woorifisa/backend/test/TestController.java
  src/main/java/com/woorifisa/backend/test/TestService.java
  src/main/java/com/woorifisa/backend/test/TestServiceImpl.java
Labels: enhancement

#14 feat: Main 패키지 기본 설정 & fix: testService @Service 추가
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/main/repository/MainRepository.java
  src/main/java/com/woorifisa/backend/main/service/MainService.java
  src/main/java/com/woorifisa/backend/main/service/MainServiceImpl.java
  src/main/java/com/woorifisa/backend/test/TestService.java
Labels: enhancement

#15 feat: setter 애노테이션 추가 & feat: Product 패키지 기본 설정
  src/main/java/com/woorifisa/backend/common/entity/Product.java
  src/main/java/com/woorifisa/backend/product/ProductController.java
  src/main/java/com/woorifisa/backend/product/ProductRepository.java
  src/main/java/com/woorifisa/backend/product/ProductService.java
  src/main/java/com/woorifisa/backend/product/ProductServiceImpl.java
Labels: enhancement

#17 feat : swagger annotation 예제 추가
  src/main/java/com/woorifisa/backend/test/TestController.java
Labels: enhancement

#19 ModelMapperConfig 설정 및 Product테이블 구조 변경 및 Main View 기능 구현
  src/main/java/com/woorifisa/backend/common/config/ModelMapperConfig.java
  src/main/java/com/woorifisa/backend/common/dto/ProductDTO.java
  src/main/java/com/woorifisa/backend/common/entity/Product.java
  src/main/java/com/woorifisa/backend/common/repository/ProductRepository.java
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/main/service/MainService.java
  src/main/java/com/woorifisa/backend/main/service/MainServiceImpl.java
  src/main/java/com/woorifisa/backend/product/service/ProductServiceImpl.java
Labels: enhancement

#20 feat : 회원 관련 기능 개발 PR (로그인 정보 세션 - 쿠키 저장) & feat : 회원가입 기능 구현
  src/main/java/com/woorifisa/backend/common/repository/MemberRepository.java
  src/main/java/com/woorifisa/backend/member/controller/AuthController.java
  src/main/java/com/woorifisa/backend/member/dto/LoginDTO.java
  src/main/java/com/woorifisa/backend/member/exception/JoinException.java
  src/main/java/com/woorifisa/backend/member/exception/LoginException.java
  src/main/java/com/woorifisa/backend/member/service/AuthService.java
  src/main/java/com/woorifisa/backend/member/service/AuthServiceImpl.java
Labels: enhancement

#21 fix : TestController의 RequestMapping이 충돌 여지가 있어 삭제, AuthController RequestMapping 추가
  src/main/java/com/woorifisa/backend/member/controller/AuthController.java
  src/main/java/com/woorifisa/backend/test/TestController.java
Labels: enhancement

#22 feat: product update 추가
  src/main/java/com/woorifisa/backend/common/repository/ProductRepository.java
  src/main/java/com/woorifisa/backend/product/controller/ProductController.java
  src/main/java/com/woorifisa/backend/product/service/ProductService.java
  src/main/java/com/woorifisa/backend/product/service/ProductServiceImpl.java
Labels: enhancement

#23 feat:상품list view category별 상품list 출력 로직
  src/main/java/com/woorifisa/backend/common/repository/ProductRepository.java
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/main/exception/NoProductException.java
  src/main/java/com/woorifisa/backend/main/service/MainService.java
  src/main/java/com/woorifisa/backend/main/service/MainServiceImpl.java
Labels: enhancement

#24 feat : 로그인 시 session 생성 및 cookie 클라이언트에게 전달 후 로그인 정보 session으로 조회 기능 구현
  src/main/java/com/woorifisa/backend/common/exception/SessionNotValidException.java
  src/main/java/com/woorifisa/backend/member/controller/AuthController.java
  src/main/java/com/woorifisa/backend/member/controller/MemberInfoController.java
  src/main/java/com/woorifisa/backend/member/dto/LoginRequestDTO.java
  src/main/java/com/woorifisa/backend/member/dto/LoginResponseDTO.java
  src/main/java/com/woorifisa/backend/member/dto/LoginSessionDTO.java
  src/main/java/com/woorifisa/backend/member/dto/MemberInfoDTO.java
  src/main/java/com/woorifisa/backend/member/service/AuthService.java
  src/main/java/com/woorifisa/backend/member/service/AuthServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#25 feat : Auth (login , logout, 회원가입, getSession) 구현 & feat : MemberInfo (회원 정보 수정, 조회) 구현
  src/main/java/com/woorifisa/backend/common/repository/MemberRepository.java
  src/main/java/com/woorifisa/backend/member/controller/AuthController.java
  src/main/java/com/woorifisa/backend/member/controller/MemberInfoController.java
  src/main/java/com/woorifisa/backend/member/dto/MemberInfoDTO.java
  src/main/java/com/woorifisa/backend/member/service/AuthService.java
  src/main/java/com/woorifisa/backend/member/service/AuthServiceImpl.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoService.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoServiceImpl.java
Labels: enhancement

#27 chore : 기타 사용하지 않는 import 문 삭제 & update 관련 api post -> put 변경
  src/main/java/com/woorifisa/backend/common/repository/MemberRepository.java
  src/main/java/com/woorifisa/backend/member/controller/MemberInfoController.java
  src/main/java/com/woorifisa/backend/member/service/AuthService.java
  src/main/java/com/woorifisa/backend/member/service/AuthServiceImpl.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoService.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoServiceImpl.java
Labels: enhancement

#26 feat: 상품 조회 시 조회수 log 남기기 구현
  build.gradle
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/resources/log4j2.xml
Labels: enhancement

#28 feat:상품에 대한 리뷰 조회 & 상품에 대한 리뷰 등록
  .gitignore
  src/main/java/com/woorifisa/backend/common/repository/ProductRepository.java
  src/main/java/com/woorifisa/backend/common/repository/ReviewRepository.java
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/main/dto/ReviewPrintDTO.java
  src/main/java/com/woorifisa/backend/main/service/MainService.java
  src/main/java/com/woorifisa/backend/main/service/MainServiceImpl.java
  src/main/java/com/woorifisa/backend/manage/service/ReviewServiceImpl.java
Labels: enhancement

#29 feat:main controller swagger 설정,설명 추가
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
Labels: enhancement

#30 feat : 로그인 한 세션을 통해 해당 유저의 구독 리스트 반환 하는 api 개발
  src/main/java/com/woorifisa/backend/common/exception/NoDataExsistException.java
  src/main/java/com/woorifisa/backend/common/repository/SubscriptionRepository.java
  src/main/java/com/woorifisa/backend/member/controller/MemberInfoController.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoService.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoServiceImpl.java
Labels: enhancement

#31 결제 정보 select
  src/main/java/com/woorifisa/backend/common/repository/PaymentRepository.java
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/main/dto/PaymentPrintDTO.java
  src/main/java/com/woorifisa/backend/main/service/MainService.java
  src/main/java/com/woorifisa/backend/main/service/MainServiceImpl.java
Labels: enhancement

#32 feat: admin 회원 및 상품 전체 조회
  src/main/java/com/woorifisa/backend/common/repository/MemberRepository.java
  src/main/java/com/woorifisa/backend/common/repository/ProductRepository.java
  src/main/java/com/woorifisa/backend/manage/controller/AdminController.java
  src/main/java/com/woorifisa/backend/manage/service/AdminService.java
  src/main/java/com/woorifisa/backend/manage/service/AdminServiceImpl.java
Labels: enhancement

#34 feat : subscription list를 조회할떄 imgurl을 함께 던져주도록
  src/main/java/com/woorifisa/backend/common/dto/SubscriptionDTO.java
  src/main/java/com/woorifisa/backend/member/service/AuthServiceImpl.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoServiceImpl.java
Labels: enhancement

#35 feat: admin 회원 및 상품 삭제 기능 구현
  src/main/java/com/woorifisa/backend/common/repository/MemberRepository.java
  src/main/java/com/woorifisa/backend/common/repository/ProductRepository.java
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/manage/controller/AdminController.java
  src/main/java/com/woorifisa/backend/manage/controller/ReviewController.java
  src/main/java/com/woorifisa/backend/manage/service/AdminService.java
  src/main/java/com/woorifisa/backend/manage/service/AdminServiceImpl.java
  src/main/java/com/woorifisa/backend/manage/service/ReviewService.java
  src/main/java/com/woorifisa/backend/manage/service/ReviewServiceImpl.java
Labels: enhancement

#33 결제방식 추가 로직 구현
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/main/dto/PaymentInsertDTO.java
  src/main/java/com/woorifisa/backend/main/service/MainService.java
  src/main/java/com/woorifisa/backend/main/service/MainServiceImpl.java
Labels: enhancement

#37 feat: 사업자 상품 관리 기능 구현
  src/main/java/com/woorifisa/backend/common/repository/ProductRepository.java
  src/main/java/com/woorifisa/backend/product/controller/ProductController.java
  src/main/java/com/woorifisa/backend/product/service/ProductService.java
  src/main/java/com/woorifisa/backend/product/service/ProductServiceImpl.java
Labels: enhancement

#38 feat : 구독 취소 기능 구현 & feat : subscription 정보 조회에 상품명 추가
  src/main/java/com/woorifisa/backend/common/repository/SubscriptionRepository.java
  src/main/java/com/woorifisa/backend/member/controller/MemberInfoController.java
  src/main/java/com/woorifisa/backend/member/dto/SubscriptionResponseDTO.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoService.java
  src/main/java/com/woorifisa/backend/member/service/MemberInfoServiceImpl.java
Labels: enhancement

#39 최종 pr
  src/main/java/com/woorifisa/backend/BackendApplication.java
  src/main/java/com/woorifisa/backend/common/dto/MemberDTO.java
  src/main/java/com/woorifisa/backend/common/dto/SubscriptionDTO.java
  src/main/java/com/woorifisa/backend/common/entity/Member.java
  src/main/java/com/woorifisa/backend/common/entity/Subscription.java
  src/main/java/com/woorifisa/backend/common/repository/MemberRepository.java
  src/main/java/com/woorifisa/backend/common/repository/ReviewRepository.java
  src/main/java/com/woorifisa/backend/common/repository/SubscriptionRepository.java
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
  src/main/java/com/woorifisa/backend/main/service/MainService.java
  src/main/java/com/woorifisa/backend/main/service/MainServiceImpl.java
  src/main/java/com/woorifisa/backend/member/dto/MemberInfoDTO.java
  src/main/java/com/woorifisa/backend/member/dto/SubscriptionResponseDTO.java
Labels: enhancement

#40 feat: 구독 log 추가
  src/main/java/com/woorifisa/backend/main/controller/MainController.java
Labels: enhancement

#41 chore: http -> https 수정
  .gitignore
  src/main/java/com/woorifisa/backend/common/config/WebConfig.java
  src/main/resources/application.properties
Labels: enhancement

#42 chore: .gitignore 적용
  src/main/resources/application.properties
Labels: enhancement
